GATEWAY_IP=1
LOCATION_SERVER_IP=5
STORAGE_ONE_IP=10
STORAGE_TWO_IP=11
STORAGE_THREE_IP=12
METASERVICE_NW=105
EXTERNAL_SERVICE_IP=86.112.115.1

PUBLIC_NW_PREFIX=193.82
PRIVATE_NW_PREFIX=10.0

#Ports
STORAGE_DEFAULT_PORT=8080
LOCATION_INDEX_DEFAULT_PORT=8080
GATEWAY_INTERNAL_DEFAULT_PORT=8080
GATEWAY_EXTERNAL_DEFAULT_PORT=8080

META_SERVICE_ADDRESS=$PUBLIC_NW_PREFIX.$METASERVICE_NW.$GATEWAY_IP
META_SERVICE_PORT=8080


#Memory
# XMS = initial HEAP
# XMX = maximaler HEAP

EXTERNAL_SERVICE_XMS=32m
EXTERNAL_SERVICE_XMX=48M

META_SERVICE_GATEWAY_XMS=32m
META_SERVICE_GATEWAY_XMX=48m

META_SERVICE_CENTRAL_INDEX_XMS=32m
META_SERVICE_CENTRAL_INDEX_XMX=48m

GATEWAY_XMS=32m
GATEWAY_XMX=48m

LOCATION_INDEX_XMS=32m
LOCATION_INDEX_XMX=48m

STORAGE_XMS=64m
STORAGE_XMX=128m
