HEADERS="Accept: application/xml"

ITEM_POST_DATA='<?xml version="1.0" encoding="UTF-8"?><com.dominikdorn.tuwien.evs.rest.domain.Item xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="i0" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Item"><name xsi:type="xsd:string">1HE Intel Atom Single-CPU CSE502 Server</name><description xsi:type="xsd:string">1HE Intel Atom Single-CPU CSE502 Server</description><size xsi:type="xsd:int">1</size><placements xsi:type="org.eclipse.persistence.indirection.IndirectList"/></com.dominikdorn.tuwien.evs.rest.domain.Item>'
ITEM_PUT_DATA='
<?xml version="1.0" encoding="UTF-8"?><com.dominikdorn.tuwien.evs.rest.domain.Item xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="i0" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Item"><name xsi:type="xsd:string">XXXXXXXXXXXXXXX</name><description xsi:type="xsd:string">YYYYYYYYYYYYY</description><size xsi:type="xsd:int">1</size><placements xsi:type="org.eclipse.persistence.indirection.IndirectList"/></com.dominikdorn.tuwien.evs.rest.domain.Item>'

RACK_POST_DATA='<?xml version="1.0" encoding="UTF-8"?><com.dominikdorn.tuwien.evs.rest.domain.Rack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="i0" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Rack"><name xsi:type="xsd:string">HP Rack 10636 G2 Shock Pallet Rack</name><description xsi:type="xsd:string">Rack 19" 36U w/d/h 24in/39.8in/68.5in</description><place xsi:type="xsd:int">36</place><placements xsi:type="org.eclipse.persistence.indirection.IndirectList"/></com.dominikdorn.tuwien.evs.rest.domain.Rack>'
RACK_PUT_DATA='<?xml version="1.0" encoding="UTF-8"?><com.dominikdorn.tuwien.evs.rest.domain.Rack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="i0" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Rack"><name xsi:type="xsd:string">BlaBla Name</name><description xsi:type="xsd:string">Blabla description</description><place xsi:type="xsd:int">36</place><placements xsi:type="org.eclipse.persistence.indirection.IndirectList"/></com.dominikdorn.tuwien.evs.rest.domain.Rack>'

PLACEMENT_POST_DATA='<?xml version="1.0" encoding="UTF-8"?><com.dominikdorn.tuwien.evs.rest.domain.Placement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="i0" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Placement"><amount xsi:type="xsd:int">5</amount><storingPosition xsi:type="xsd:string">TOP</storingPosition><item id="i1" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Item"><id xsi:type="xsd:long">1</id></item><rack id="i2" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Rack"><id xsi:type="xsd:long">1</id></rack></com.dominikdorn.tuwien.evs.rest.domain.Placement>'
PLACEMENT_PUT_DATA='<?xml version="1.0" encoding="UTF-8"?><com.dominikdorn.tuwien.evs.rest.domain.Placement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="i0" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Placement"><amount xsi:type="xsd:int">5</amount><storingPosition xsi:type="xsd:string">BOTTOM</storingPosition><item id="i1" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Item"><id xsi:type="xsd:long">1</id></item><rack id="i2" xsi:type="com.dominikdorn.tuwien.evs.rest.domain.Rack"><id xsi:type="xsd:long">1</id></rack></com.dominikdorn.tuwien.evs.rest.domain.Placement>'

